#cloud-config
datasource:
  Ec2:
    strict_id: false
users:
  - default
  - name: "${user}"
    groups: wheel
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "${ssh_key}"

